myhome/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CustomerPriority__c</fullName>
        <label>Customer Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

myhome/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CurrentGenerators__c</fullName>
        <label>Current Generator(s)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

myhome/src/classes/SoslDemo.cls
public class SoslDemo{
 
    public void searchData()
    {
        
       List<List<Sobject>> lst=[find 'test' in all fields returning Account(id,name,accountnumber,CustomerPriority__c),Contact(id,name,phone),Opportunity(id,name,CurrentGenerators__c)];
       
        List<account> acclst=lst.get(0);        
        List<contact> conlst=lst.get(1);  
        List<opportunity> opplst=lst.get(2);  
  
        for(Account acc: acclst)
        {
            system.debug('acc id:'+acc.id);
            system.debug('acc name'+acc.name);
            system.debug('acc prority'+acc.CustomerPriority__c);
        }
       for(Contact con: conlst )
        {
            system.debug('con id:'+con.id);
            system.debug('con name'+con.name);
        }
       
        
        
    }
    
    

}