myhome/src/objects/college__c.object
<CustomObject>
    <label>college</label>
    <nameField>
        <label>college Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>college</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

myhome/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>collegename__c</fullName>
        <label>college</label>
        <referenceTo>college__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

myhome/src/classes/ListDemo1.cls
public class ListDemo1{

 public void getAccountInfo()
 {
     
     integer x=5;
     
     //select id,name,(select id,name from Students__r ) from college__c
     //
     //select id,name,(select id,name from contacts) from account
     //select id,name,(select id,name from students__r) from College__c
       List<Account> acclst=[select id,name,accountnumber from account limit 5];
     
       for(Account acc : acclst)
       {
           
           system.debug('acc id--'+acc.id);
             system.debug('acc name--'+acc.name);
             system.debug('acc number--'+acc.accountnumber);
             //system.debug('acc id--'+acc.id);
           
       }
 }   
    
}